### PR TITLE
Update C applet 1

### PR DESCRIPTION
**Pull request by info-cppsp**
Added an about dialog, copied from mate-sensors-applet.
Added possibility to use image.
Added tooltip to image.

Anything else you would like to see in this example applet?

### CODE REVIEW

**Review by lukefromdc — APPROVED** [review]
This works, adds an icon and the "about" dialog works. Note that on MATE 1.20 with gtk 3.22, the python applet does NOT work without https://github.com/mate-desktop/mate-university/pull/10 which was just merged but not included in the test package for this PR

**Comment by info-cppsp** [comment]
ofc it doesn't work without that PR.
test package? what do you mean?

**Comment by lukefromdc** [comment]
I just downloaded a tarball from your repo, built and ran it. Tarball  was "mate-university-cappletud.zip"

**Comment by info-cppsp** [comment]
OK, I get it. Sorry, I still have to make some organizational PRs to make this repo work properly.
I didn't want to include the gtk commit in this PR as well, so.
But yes, you should have that as well.
Let me force push an update, now that the gtk PR is merged.

**Comment by raveit65** [comment]
Not related to PR but what weird dependencies has this package?
```
checking for CFPreferencesCopyAppValue... no
checking for CFLocaleCopyCurrent... no
```
I can't solve this dependencies in fedora.
```
[root@mother rave]# dnf provides */CFPreferences.h
Last metadata expiration check: 1:11:09 ago on Sat Mar  3 08:30:00 2018.
Error: No Matches found
[root@mother rave]# dnf provides */CFLocale.h     
Last metadata expiration check: 1:11:59 ago on Sat Mar  3 08:30:00 2018.
Error: No Matches found
```

**Review by raveit65 — CHANGES_REQUESTED** [review]
make distcheck fails with this applet.
```
make[3]: Entering directory '/media/Work/Progamme-linux/Mate-Desktop/git-version/github-matedesktop/mate-university-dist/mate-university-1.7.0/_build/sub/applet-c'
gcc -DHAVE_CONFIG_H -I. -I../../../applet-c -I..  -I/usr/include/mate-panel-4.0/libmate-panel-applet -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libdrm -I/usr/include/harfbuzz -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -pthread  -I../../../applet-c -DMATELOCALEDIR=\""/media/Work/Progamme-linux/Mate-Desktop/git-version/github-matedesktop/mate-university-dist/mate-university-1.7.0/_inst/share/locale"\"    -g -O2 -MT university_applet-applet.o -MD -MP -MF .deps/university_applet-applet.Tpo -c -o university_applet-applet.o `test -f 'applet.c' || echo '../../../applet-c/'`applet.c
../../../applet-c/applet.c:29:10: fatal error: applet.h: No such file or directory
 #include "applet.h"
          ^~~~~~~~~~
compilation terminated.
make[3]: *** [Makefile:452: university_applet-applet.o] Error 1
make[3]: Leaving directory '/media/Work/Progamme-linux/Mate-Desktop/git-version/github-matedesktop/mate-university-dist/mate-university-1.7.0/_build/sub/applet-c'
make[2]: *** [Makefile:407: all-recursive] Error 1
make[2]: Leaving directory '/media/Work/Progamme-linux/Mate-Desktop/git-version/github-matedesktop/mate-university-dist/mate-university-1.7.0/_build/sub'
make[1]: *** [Makefile:348: all] Error 2
make[1]: Leaving directory '/media/Work/Progamme-linux/Mate-Desktop/git-version/github-matedesktop/mate-university-dist/mate-university-1.7.0/_build/sub'
make: *** [Makefile:617: distcheck] Error 1
```

**Comment by raveit65** [comment]
I will push the fix for missing README error with distcheck, in result you will see this error.

**Comment by raveit65** [comment]
Repo reached EOL status.

**Pull request closed without merging**
