### PR TITLE
Make GTK+ 3 default

### PR DESCRIPTION
**Pull request by info-cppsp**

### CODE REVIEW

**Comment by info-cppsp** [comment]
This repo used to have the option to chose between gtk+ 2 and 3.
Now it should be 3 only.
Please review.

**Comment by raveit65** [comment]
As maintainer of this repo you should be able to create a new branch for a PR here, or does that not work?

**Comment by info-cppsp** [comment]
sure. would that be better?

**Comment by raveit65** [comment]
It saves your time if you don't need to fork it....
I wasn't sure that you know that you have acls.

**Comment by raveit65** [comment]
Btw. we create our tarballs with *./autogen.sh && make && make distcheck*
*make distcheck* fails for several reasons.
First issue is a missing README.
I suggest to create a symlink to README.md like we do that in mate-calc.
After that you can delete this hackisch line from 
https://github.com/mate-desktop/mate-university/blob/master/Makefile.am#L4

At least i am not the perfect reviewer for a package which i don't use for fedora and never build/installed in life.

**Comment by info-cppsp** [comment]
> make distcheck

right...
thanks for the tip on README - I was wondering how to do it
I'll fix them in another PR.

**Comment by monsta** [comment]
Should we actually package this? I thought it was like of a set of examples for people to look here on Github.

**Comment by info-cppsp** [comment]
yes, that is correct.
I don't think that this should be available through 'normal' means, like a package manager.

still, it shouldn't have build errors, even with distcheck.

**Comment by info-cppsp** [comment]
@lukefromdc @sc0w 
If I could ask you to make a review.
I can't just add you, like I have done with the others.
Thanks.

**Comment by raveit65** [comment]
I added core-team and code-reviewer groups to this repo.

**Comment by info-cppsp** [comment]
thank you, now I can add them :)

I have checked the distcheck and I'm going to make a PR with that later.
the .pot file wasn't generated bc of a typo.
someone wrote cairo-text.c instead of the correct cairo-test.c

**Comment by monsta** [comment]
We even have translations in sample programs O_o

**Comment by info-cppsp** [comment]
not much though.
I'm not sure if it should be left as is, updated with transifex or removed...

**Comment by monsta** [comment]
Drop it, this repo isn't on Transifex, and I think it never was.

**Comment by raveit65** [comment]
Without releasing it any translator will see it, so adding it to transifex doesn't make any sense.

**Comment by info-cppsp** [comment]
ok

**Comment by monsta** [comment]
Hmm... did you somehow force-push the master branch today...?

**Comment by info-cppsp** [comment]
yes. I wanted to fix a couple of commits so...
I know it's not nice...
what happened?

**Comment by info-cppsp** [comment]
I have learned never to use 'Create a merge commit' and how to fix it...

**Comment by raveit65** [comment]
yes

**Comment by raveit65** [comment]
Btw. I think we should update version and NEWS after the re-work is done, so that people can see that the package is under development.
Also tagging should be done.

**Comment by raveit65** [comment]
> what happened? was there any side effect? I checked github, it took my changes without problems.

Don't do that please, you broke every local repo from other people.

A 'git pull' on master from today, (sorry. in german)
```
[rave@mother mate-university]$ git pull
remote: Counting objects: 57, done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 57 (delta 22), reused 49 (delta 15), pack-reused 0
Entpacke Objekte: 100% (57/57), Fertig.
Von github.com:mate-desktop/mate-university
 + c4f72f2...9425793 master     -> origin/master  (Aktualisierung erzwungen)
automatischer Merge von configure.ac
KONFLIKT (Inhalt): Merge-Konflikt in configure.ac
automatischer Merge von cairo-test/cairo-test.c
KONFLIKT (hinzufügen/hinzufügen): Merge-Konflikt in cairo-test/cairo-test.c
Automatischer Merge fehlgeschlagen; beheben Sie die Konflikte und committen Sie dann das Ergebnis.
```

**Comment by raveit65** [comment]
The only way to solve it here, isto fix it by hand or to delete the local repo.
In result all possible local changes are lost.
People will love you for this ;)

**Comment by info-cppsp** [comment]
I know about this.
This repo has been last updated in 2014.
I am not really concerned.
At least people will see that it is updated...
There are 2 more things that are easier / better to do with rebase, so...
I am writing up a plan, so I don't have to do this again...

I wrote earlier that I have fixed the README and the distcheck.
I will add that as well.

**Comment by raveit65** [comment]
ReadME is already commited.

**Comment by raveit65** [comment]
To say it in clear words.
Doing a 'git push -f' on master or a stable branch is a NOGO.

**Comment by info-cppsp** [comment]
OK, I'll make one big revert PR.

**Comment by raveit65** [comment]
What you want revert?
Local commits you can edit with 'git rebase'
Only doing a 'git push -f' after that is ugly.

**Comment by raveit65** [comment]
Edit:
Editing a commit which is already push isn't nice.
Of cource you can edit every local commit before you push them.
Hope this makes it clear.....

**Pull request merged**
